export const DEFAULT_PROMOS = [
  {
    id: 'promo-kovboi10',
    code: 'KOVBOI10',
    type: 'percent',
    value: 10,
    label: '−10%',
    minSubtotal: null,
    maxUses: null,
    expiresAt: null,
    active: true,
  },
  {
    id: 'promo-cowboys15',
    code: 'COWBOYS15',
    type: 'percent',
    value: 15,
    label: '−15%',
    minSubtotal: null,
    maxUses: 100,
    expiresAt: null,
    active: true,
  },
  {
    id: 'promo-erd500',
    code: 'ERD500',
    type: 'fixed',
    value: 500,
    label: '−500 ₽',
    minSubtotal: 3000,
    maxUses: 50,
    expiresAt: null,
    active: true,
  },
];
